version: '3'
services:

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: prontuarioDB
      POSTGRES_USER: userTeste
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
